# Generated by Django 2.2.3 on 2019-08-01 14:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_book_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', 'language']},
        ),
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['book', 'status']},
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this specific book', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Enter a book genre (e.g. Science Fiction)', max_length=200, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text="Enter the book's language (e.g. English, French, Japanese etc.)", max_length=200, verbose_name='Language'),
        ),
    ]
